CREATE TABLE IF NOT EXISTS RATING_MPA (
                            RATING_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            RATING_NAME varchar (50)
);

CREATE TABLE IF NOT EXISTS FILMS (
                       FILM_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       FILM_NAME varchar (50),
                       DESCRIPTION varchar (200),
                       REALISE_DATE date,
                       RATING INTEGER REFERENCES RATING_MPA (RATING_ID),
                       DURATION INTEGER
);

CREATE TABLE IF NOT EXISTS GENRE (
                       GENRE_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       GENRE_NAME varchar (50)
);

CREATE TABLE IF NOT EXISTS FILM_GENRE (
                            FILM_GENRE_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            FILM_ID INTEGER REFERENCES FILMS (FILM_ID),
                            GENRE_ID INTEGER REFERENCES GENRE (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS USERS (
                       USER_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       USER_EMAIL varchar (50) NOT null,
                       BIRTHDAY date NOT null,
                       USER_LOGIN varchar (50) NOT null,
                       USER_NAME varchar (50)
);

CREATE TABLE IF NOT EXISTS LIKES (
                       LIKES_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       FILM_ID INTEGER REFERENCES FILMS (FILM_ID),
                       USER_ID INTEGER REFERENCES USERS (USER_ID)
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP (
                            FRIENDSHIP_ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            USER_ID INTEGER REFERENCES USERS (USER_ID),
                            FRIEND_ID INTEGER REFERENCES USERS (USER_ID)
);