
-- Таблицы для хранения Film

create TABLE IF NOT EXISTS mpa (
id integer primary key,
name varchar (20)
);

create table if not exists genre (
id integer primary key,
name varchar (50)
);

create TABLE IF NOT EXISTS film (
id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
name VARCHAR(50),
description VARCHAR(200),
realise_date DATE,
duration INTEGER,
mpa_id INTEGER ,
FOREIGN KEY (mpa_id) REFERENCES mpa (id)
);

create TABLE IF NOT EXISTS film_genre (
film_id INTEGER,
genre_id INTEGER,
FOREIGN KEY (film_id) REFERENCES film (id),
FOREIGN KEY (genre_id) REFERENCES genre (id)
);

--Таблицы для хранения User

create TABLE IF NOT EXISTS USERS (
ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
EMAIL varchar (50) NOT null,
BIRTHDAY date NOT null,
LOGIN varchar (50) NOT null,
NAME varchar (50)
);

create TABLE IF NOT EXISTS LIKES (
FILM_ID INTEGER ,
USER_ID INTEGER,
FOREIGN KEY (FILM_ID)  REFERENCES FILM (ID),
FOREIGN KEY (USER_ID)  REFERENCES USERS (ID)
);

create TABLE IF NOT EXISTS FRIENDSHIP (
USER_ID INTEGER ,
FRIEND_ID INTEGER,
FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
FOREIGN KEY (FRIEND_ID) REFERENCES USERS(ID)
);